version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: taximetro-digital:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NO_AT_BRIDGE=1
